env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-console: 0
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
